Sk yh prohibit duplicate items
the-collab-lab/tcl-27-smart-shopping-list pull request #21
Opened 2021-07-28 19:28 UTC by AirZT11

## Description

* When submitting a new item, we checked the database to see if there were any duplicates compared to what was about to be submitted
* Alerted user if they were about to submit a duplicate item and prohibited the item from being submitted to the database
* Used the toLowerCase() method and Regex to ignore case and punctuations when comparing items about to be submitted and items in the database
* Refactored changeHandler function to make it more readable

## Related Issue
Closes #6

## Acceptance Criteria
https://github.com/the-collab-lab/tcl-27-smart-shopping-list/issues/6

6. As a user, I want to be alerted when I’m entering an item that is the same as something already on my list so I can avoid duplicate items.

AC:
* Show an error message if the user tries to submit a new item that has the exact same name as an existing item
* Show an error message if the user tries to submit a new item that has the same name as an existing item, where capitalization has been normalized and punctuation has been removed
* The user’s original input should be what gets saved in the database

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

From your terminal, checkout this branch with git checkout sk-yh-prohibit-duplicate-items and check that branch out with git checkout sk-yh-prohibit-duplicate-items

Add an item that is already included in the list and make sure that you are alerted that it is a duplicate item. Also try adding punctuation or casing the item to check that it disregards the punctuation/case and still alerts you that the item is a duplicate.

2021-07-29 23:05 UTC, tcelovsky commented on src/components/AddItem.js
> +          .replace(/[ *.,@#!$%&;:{}=\-_`~()]/g, ''),
Good call using Regex to remove punctuation! I always have to spend time googling how to use it correctly!

2021-07-29 23:07 UTC, tcelovsky commented on src/components/AddItem.js
>    submitHandler = (event) => {
We are going to have some merge conflicts here, because we had to make some updates in our branch to account for the changes to the data structure. Happy to work through that together! The updates you two made look great and looks like the functionality will work perfectly!

2021-07-29 23:11 UTC, tcelovsky commented on src/components/GroceryCard.js
> +      <p>LAST PURCHASE DATE: {item.lastPurchase.toDate().toDateString()}</p>
Dani and I thought that maybe last purchase date should be stringified when it's being saved to the database, but would love to know what you think about that.

2021-07-29 23:15 UTC, tcelovsky reviewed
Great job using Rejex! I always struggle with that! We probably will have merge conflicts related to the changes in the data structure that we made. It took a little while for us to figure out how to correctly fetch the right data from Firestore, happy to work through the merge conflicts and any Firestore related updates together!

2021-07-30 02:42 UTC, YolandaHaynes commented on src/components/AddItem.js
>    submitHandler = (event) => {
Yea for sure! I definitely would love a walk through to fix the merge conflicts.

2021-07-30 17:22 UTC, tcelovsky approved these changes

2021-07-30 21:28 UTC, AirZT11 commented on src/components/GroceryCard.js
> +      <p>LAST PURCHASE DATE: {item.lastPurchase.toDate().toDateString()}</p>
Definitely agree! I'll make sure to incorporate that!

2021-07-30 22:22 UTC, DPoplin commented on src/components/AddItem.js
> +          .replace(/[ *.,@#!$%&;:{}=\-_`~()]/g, ''),
Ooh regex. I use it super infrequently but this made me go do a little refresher. Love it.

2021-07-30 22:24 UTC, DPoplin commented on src/components/AddItem.js
> +        });
Definitely going to be some merge conflicts here too with the data structure -- mostly looking at the places where userToken and the individual items get saved now.

2021-07-30 22:24 UTC, DPoplin commented on src/components/AddItem.js
> +    this.setState({ [event.target.name]: event.target.value });
This refactoring makes things to much cleaner. Thank you!

2021-07-30 22:25 UTC, DPoplin commented on src/components/GroceryCard.js
> +      <p>LAST PURCHASE DATE: {item.lastPurchase.toDate().toDateString()}</p>
+1 to this idea. We found that there were some issues with retrieving data from Firestore if not stringified.

2021-07-30 22:33 UTC, AirZT11 commented on src/components/AddItem.js
> +        });
Yeah I definitely noticed that. I already played around with it and it's not going to be too much of a problem when adjusting the code to adapt to the new structure.

2021-07-30 22:34 UTC, DPoplin reviewed
Hey y'all! Great work this week. Tatyana and I talked through this PR a little bit and the conflicts we expect to arise. 
I also can't seem to get this branch to compile locally -- getting this error: `./src/App.js
Module not found: Can't resolve 'firebase/app' in '/Users/dpoplin/Desktop/tcl-27-smart-shopping-list/src'` I'm not sure if anyone else is running into this error during code reviews.  

When running from the link I am also getting errors when attempting to add an item:
`TypeError: Cannot read property 'toLowerCase' of undefined`

2021-07-30 22:44 UTC, DPoplin approved these changes

2021-07-31 01:47 UTC, lyleschemmerling requested changes
This looks good except for the "punctuation" that escapes the regex. Consider using something like `/[^\w\s\d]/g` (ish, I avoid regex like the plague so need to check me) to exclude everything that isn't a word, space, or digit instead of checking for a list of special characters.

2021-07-31 01:47 UTC, lyleschemmerling commented on src/components/AddItem.js
> +        .replace(/[ *.,@#!$%&;:{}=\-_`~()]/g, '');
Note that the following gets past the filter `B+AN+AN+AS` for `bananas`

2021-07-31 01:47 UTC, lyleschemmerling commented on src/components/AddItem.js
> +          userToken: 'josef heron mudd',
Do we still want this hard-coded value?

2021-07-31 14:28 UTC, lyleschemmerling approved these changes

2021-07-31 15:03 UTC, merged