Tc dp join shopping list
the-collab-lab/tcl-27-smart-shopping-list pull request #23
Opened 2021-07-29 01:31 UTC by tcelovsky

Co-authored-by: Dani Poplin <danih37@gmail.com>

## Description

This PR updates our data structure, adds a new Home.js component, updates GroceryCard.js, and updates AddItem.js.

#### Data Structure

We updated Firestore database such that the item lists are created under a user token document, in the items collection. This allows us to search the database for an individual user token and fetch the data object containing list items. 

#### Home.js

We created a new home component that allows the user to either create a new list or join an existing list by entering a user token. If the user wants to join an existing list, we confirm that the list already exists in the database, if so, we save the token to `localStorage`. We then query the database for the entered token, fetch the existing list items and redirect the user to the list view. 

#### GroceryCard.js

We updated the unordered list items to display the data based on the new data structure in the database. 

#### AddItem.js

We updated add item component to save the data to the database in the new structure and to clear the add item form upon submission. 

#### App.js

We updated the `Switch` statement such that the user is not redirected to the list view if the user is not logged in. 

## Related Issue

Closes #5 

## [Acceptance Criteria](https://github.com/the-collab-lab/tcl-27-smart-shopping-list/issues/5)

- When the user does not already have a token in localStorage, on the onboarding/home screen, a simple form is displayed that allows the user to enter a token
- Entering the token and hitting submit saves the token to localStorage, effectively giving them joint control of the list
- On submit, show an error if the token does not exist
- If they get an error message, allow them to try again or create a new list

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

1. First, from your terminal, pull from the `main` branch with `git pull origin main`
2. From your terminal, pull down this branch with `git pull origin tc-dp-join-shopping-list` and check that branch out with `git checkout tc-dp-join-shopping-list`
3. Ensure that a simple form is displayed on the home screen to allow the user to enter a token if the user is not already logged in. For this step, run `localStorage.clear()` in your console. 
4. Go to the [Firestore database](https://console.firebase.google.com/u/0/project/tcl-27-shopping-list/firestore/data/~2Fgroceries) and copy one of the tokens listed in the collection.
5. Enter the copied token in the form on the home page and hit submit. 
6. Check the the same token is saved to your `localStorage` by running `localStorage` in your console. 
7. On submit, you should be redirected to the list view.
8. Clear your `localStorage` by running `localStorage.clear()` in your console.
9. Enter a random word in the form on the home page an hit submit.
10. Ensure that an error message (an alert) is displayed saying that a token is not found.

2021-07-29 03:25 UTC, AirZT11 commented on src/components/containers/Home.js
> +export default Home;
Fantastic job creating this new component and building your token validation logic! Appreciate the heavy lifting and creating this extra component!!

2021-07-29 04:59 UTC, AirZT11 reviewed
Great job on this issue Dani and Tatyana! I really like how you built the 'login' portion into a new Home component. Really appreciate ya'll for putting in so much work, I know it was a handful! Thanks again!!!

2021-07-29 04:59 UTC, AirZT11 commented on src/components/containers/Home.js
> +    this.getTokens();
Can `this.getTokens()` live in a componentDidMount() lifecycle method? That way it fetches the tokens when the component mounts before render. I think this is fine either way as it fetches the tokens right when a user starts typing though!

2021-07-29 04:59 UTC, AirZT11 commented on src/components/containers/Home.js
> +      this.props.setLoggedIn(true);
Nice work getting the setLoggedIn state passed down as a prop!

2021-07-29 04:59 UTC, AirZT11 commented on src/App.js
> +          {!loggedIn && <Redirect exact path="/" />}
I was getting a warning here in the console: _Warning: Failed prop type: The prop `to` is marked as required in `Redirect`, but its value is `undefined`_. I believe `<Redirect/>` takes a `to` prop and not an `exact path` prop

2021-07-29 04:59 UTC, AirZT11 commented on src/App.js
> +    }
Nice work on building this conditional statement! Really like how ya'll set up the database so a list can be associated with a unique token! Btw, I don't think we need the else statement, right?

2021-07-29 04:59 UTC, AirZT11 commented on src/components/AddItem.js
> +    }
This is so well done! I love how a user can now set a document as a unique token and then store items into an items collection nested inside. This is sick!!

One thing we could do later is possibly refactor the `fb.firestore().collection('groceries').doc(localStorage.getItem('token'))` and set it to a variable to follow the DRY principle.

2021-07-29 04:59 UTC, AirZT11 commented on src/components/containers/GroceryContainer.js
> +    };
Sorry, I'm a little confused about this conditional. As `isMounted` is initially set to true, doesn't `getGroceries()` always get called? I might be missing something here though. Mind explaining this portion to me when you get a chance? Thanks!!

2021-07-29 21:54 UTC, tcelovsky commented on src/App.js
> +    }
We are only saving to the database if the user is logged in and we were thinking that maybe we should have the else statement in case the user is not logged in, then we can either trigger an alert or redirect. But I think you make a good point that it may not be necessary at all! Definitely will think about this and figure out what to do here.

2021-07-29 21:55 UTC, tcelovsky commented on src/App.js
> +          {!loggedIn && <Redirect exact path="/" />}
Ah good point, I missed that! I'll update before we merge the branch. Thank you!

2021-07-29 21:55 UTC, tcelovsky commented on src/components/AddItem.js
> +    }
Definitely agree with that! There probably are a few places where we can refactor in the future.

2021-07-29 22:09 UTC, tcelovsky commented on src/components/containers/GroceryContainer.js
> +    };
No problem at all! We were getting an error message here that said "Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function." When looking into this we realized that this has to do with [useEffect clean up functions](https://reactjs.org/docs/hooks-effect.html). I don't know React hooks well enough, but my understanding is that if we return a function within the useEffect hook, that function will execute when the component gets dismounted. It seems that because getGroceries was inside useEffect, we were attempting to fetch from the database (and update state) when getGroceries was unmounting, which caused the error. By setting isMounted to false right after fetching from the database we are preventing that second attempt at fetching. Happy to talk more over Zoom, not sure that I'm explaining it well enough here :)

2021-07-29 22:11 UTC, tcelovsky commented on src/components/containers/Home.js
> +    this.getTokens();
Good point, let me think about that more. I wasn't sure that we would want to fetch from the database right away, unless the user wants to use an existing token. But I'm happy to update and put this in componentDidMount.

2021-07-29 22:11 UTC, tcelovsky commented on src/components/containers/Home.js
> +      this.props.setLoggedIn(true);
:) thanks!

2021-07-29 22:36 UTC, AirZT11 commented on src/components/containers/GroceryContainer.js
> +    };
Wowww that is crazy! I was wondering why that error was coming up! Great job researching this and finding a solution. Was this happening when you submitted an item and quickly checked the /list route? I think it's due to the async functionality of fetching from firestore and it trying to setGrocery(groceries)

2021-07-29 22:41 UTC, AirZT11 commented on src/App.js
> +    }
Ahhh that so very true. Good thinking. Will have to keep that in mind while moving through the next user stories. Thanks!

2021-07-29 22:42 UTC, AirZT11 approved these changes

2021-07-29 23:33 UTC, tcelovsky commented on src/components/containers/GroceryContainer.js
> +    };
Yeah, you are probably right that it's related to the async functionality. It was interesting to get that error - from reading about it, it doesn't seem to come up very often. Definitely good learning experience!

2021-07-30 02:37 UTC, YolandaHaynes approved these changes
You guys rock changing the firestore database! This is out of my element of understanding, so if you have time, I would love to see a breakdown and a demo of what you guys did and the challenges you bumped into. 
  So far, everything checks out and was working on my end when I tried out various tokens. Only issue I had was a user error, I had extra spaces (I was using copy/paste) on acceptable tokens, and it returned as an invalid token which probably won't occur when a user actually types in the token.

2021-07-30 02:42 UTC, lyleschemmerling commented on src/App.js
> +    if (localStorage) {
The global variable localStorage should always be present and therefore always true. Did you mean `if (localStorage.getItem('token'))`?

2021-07-30 03:35 UTC, lyleschemmerling commented
Its not something that needs fixed for this issue, But "Home" and the "Bottom Nav" are always present since they sit outside of the scope of the router. In the case of home this is mildly confusing as I am always presented with enter a token or generate a new one regardless of my state.  I bring this up also because the bottom nav being always present means I can get to the add page all the time. What happens when I don't have a token?

2021-07-30 03:36 UTC, lyleschemmerling requested changes
We should fix the issue with firing the database queries on every type event of the input box before merging.

2021-07-30 03:36 UTC, lyleschemmerling commented on src/components/containers/Home.js
> +  handleChange = (e) => {
This event fires on every keystroke in the input text box. That in turn calls and queries firestore for all of the tokens in the database, and then updates the local state with the tokens on each keypress. This is very expensive.

You could move the caching of tokens in state to when the component loads, but you probably don't need to do that. I think you can move the logic of `getTokens` into `handleClick`. There's a small chance of waiting on the query when that happens, but I don't think we need to worry too much about that for this app.

2021-07-30 14:17 UTC, tcelovsky commented on src/App.js
> +    if (localStorage) {
Ah got it, thank you! I updated to `if (localStorage.getItem('token'))`.

2021-07-30 14:41 UTC, tcelovsky commented on src/components/containers/Home.js
> +  handleChange = (e) => {
Thanks Lyle! Sam also pointed out the same thing. I moved `this.getTokens()` to `componentDitMount()` to avoid having a  delay.

2021-07-30 22:50 UTC, DPoplin commented on src/App.js
> +    if (localStorage) {
That is a great call out. Thank you Lyle!

2021-07-31 01:09 UTC, lyleschemmerling approved these changes

2021-07-31 15:03 UTC, merged