How to start tracking purchase dates: new and improved schema! You don't want to miss this
the-collab-lab/tcl-27-smart-shopping-list pull request #28
Opened 2021-08-10 22:27 UTC by DPoplin

Updated DB schema to track number of purchases and purchase frequency metrics
co-authored-by: Yolanda Haynes <yhaynes@giyo.us>

## Description

We updated the firebase collection schema in order to keep a record of the number of purchases of an item, item frequency, and an estimated timeframe when the item should be purchased next. The DB collections can now keep track of the users items they frequently buy, and gives them an estimate of when the next time they may need to buy the item.

## Related Issue

Closes #10 

## Acceptance Criteria

- [x] When a purchase is recorded, the estimated number of days until the next purchase date should be calculated and recorded in the database

## Type of Changes

| 	| Type                   	|
| --- | -------------------------- |
|	| :bug: Bug fix          	|
|  ✓ | :sparkles: New feature 	|
|	| :hammer: Refactoring   	|
|	| :100: Add tests        	|
|	| :link: Update dependencies |
|	| :scroll: Docs          	|

## Updates

We've updated the firestore database schema by adding in the `actualPurchaseInterval`, `numberOfPurchases`, `nextPurchaseDate`, and updated `frequency` to `estimatedFrequency`. The schema was updated in order to use  the `/src/lib/estimates.js` calculations.

## Testing Steps / QA Criteria
- From your terminal, pull down this branch with git pull origin `yh-dp-estimate-next-purchase` and check that branch out with git checkout `yh-dp-estimate-next-purchase`
- Then npm start to launch the app.
- Fill out the form with a new item. Make sure it adds it to the list and that item appears in the firestore grocery collection.
- Check the item as if you would purchased it, go into firestore collections and when you see your item, change the checkedTime date at least 24 hours in the past and then refresh the app.
- Check the database, you should see the fields update. Try it multiple times of the same items to see the frequency and estimated next purchase date change.

2021-08-11 15:04 UTC, tcelovsky approved these changes
I think you did a great job completing the asks in this user story! The app is working exactly as expected and I am looking forward to talking through the logic during our walkthrough!

2021-08-12 15:24 UTC, AirZT11 commented on src/components/GroceryCard.js
> +      const oneFullDayInMS = 24 * 60 * 60 * 1000;
Thanks for changing the name to specify MS! Definitely more understandable this way

2021-08-12 15:26 UTC, AirZT11 commented on src/components/GroceryCard.js
> +          );
I like the use of Math.round to get a whole number. Makes the calculations much more succinct

2021-08-12 16:29 UTC, AirZT11 requested changes
Nice job on this user story! This was the meat and potatoes of this project so props to implementing the estimates.js module. I would just check back on the GroceryCard component to review the `item.purchaseFrequency` field so that the `calculateEstimate` method gives you an accurate calculation. Thanks @DPoplin + @YolandaHaynes !!

2021-08-12 16:29 UTC, AirZT11 commented on src/components/GroceryCard.js
> +          item.purchaseFrequency,
I don't think `purchaseFrequency` exists as a field in the database. Did you mean to use the `estimatedFrequency` field value?

2021-08-12 16:29 UTC, AirZT11 commented on src/components/GroceryCard.js
> +        );
Awesome job on creating this variable to calculate the date in which to find the next estimated purchase date. I also like the use of the `fromMillis` method to convert MS to dates!

2021-08-12 16:29 UTC, AirZT11 commented on src/components/AddItem.js
> +          }
Nice job on this conditional logic. I feel like I would've missed this haha!

2021-08-12 21:33 UTC, DPoplin commented on src/components/GroceryCard.js
> +          item.purchaseFrequency,
Great catch Sam! Corrected.

2021-08-12 21:51 UTC, AirZT11 approved these changes

2021-08-13 22:18 UTC, lyleschemmerling approved these changes
I like this. Good stuff.

2021-08-13 22:43 UTC, lyleschemmerling reviewed
Am I supposed to being seeing the next purchase date? It looks like it is missing.

2021-08-13 22:46 UTC, lyleschemmerling approved these changes
It's friday and I forgot how to follow instructions. This works.

2021-08-14 16:30 UTC, merged